name: StyleCI
on: [push, pull_request]
jobs:
  Analyze:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: "7.4"
        extensions: curl
    - name: analyze code with StyleCI
      uses: nathane/styleci-action@main # "@0.6" branch and "@v0.6.3" tag are also available
      with:
        styleci_api_key: ${{ secrets.STYLECI_API_KEY }} # required
        # options: '--no-interaction --dry-run'         # optional
        # directory: './'                               # optional
